### ISSUE TITLE
TF2.0 incompatibility

### ISSUE THREAD

**Issue by francoisruty** [tensorflow/graphics#15]
Hello, I'm using tensorflow-graphics with tensorflow 2.0.

I'm trying to use tfg.geometry.representation.mesh.normals.vertex_normals but I'm getting:

  File "/usr/local/lib/python3.5/dist-packages/tensorflow_graphics/util/shape.py", line 135, in _get_dim
    return tensor.shape[axis].value
AttributeError: 'int' object has no attribute 'value'

.shape indeed returns an integer, .value is undefined, so I think there is a typo in source code

This link: https://github.com/tensorflow/tensorflow/issues/28444
suggests that earlier versions of tensorflows had this attribute

Shall I make a PR to fix this? I'm not sure about how to maintain retrocompatibility though, I guess testing the existence of this attribute would be a little bit "dirty"

**Comment by francoisruty** [comment]
Mmmmm I've just looked closer to the source code:

def _get_dim(tensor, axis):
  """Returns dimensionality of a tensor for a given axis."""
  if tf.executing_eagerly():
    return int(tf.shape(input=tensor).numpy()[axis])
  else:
    return tensor.shape[axis].value


so it seems you guys already accounted for TF2 difference, yet in my case I'm in TF2.0 and the second part of the if is traversed

I've seen other weird stuff in TF2, AKA error messages that seem to supposedly pop up only when tf is not executing eagerly (which shouldn't happen in TF2 since eager is execution is ON by default).
I have a feeling that tf.executing_eagerly() is not a reliable way to check for TF1/TF2 environment.
It seems to me that the source code author assumes that 
! tf.executing_eagerly() => not using TF2
but that may not be right

**Comment by julienvalentin** [comment]
Hi!

We actually test for graph and eager mode execution for both TF1 and TF2, but it's possible that something slipped. In case you did not resolve it by then, I will have time to get to this next week.

Best.

**Comment by francoisruty** [comment]
Hello, no hurry, in the meantime I've updated my Dockerfile to just do a sed replace in shape.py

Let me know if you need anything from me, I can help

**Comment by francoisruty** [comment]
@julienvalentin sorry for spamming here can I send you an email about rasterization with TFG?

**Comment by julienvalentin** [comment]
sure, my email is julienvalentin@google.com

**Comment by julienvalentin** [comment]
Hi Francois,

Can I ask you to create a functional example illustrating the problem using colab.sandbox.google.com?
That would help reproducing / fixing.

Thanks!

**Comment by francoisruty** [comment]
sure, I'll send you something in coming days

**Comment by francoisruty** [comment]
Ok so I have difficulties setting up a simple program that reproduces the error. I only get the error with my complex geometry.
If I try to use simpler geometry, I don't get this error.

I thought I would just save the vertices and triangles in a .npy file, but I came across a TF2 bug with .numpy() method (https://github.com/tensorflow/tensorflow/issues/27519) so I can't even convert this geometry to a numpy array, and thus I can't use np.save

Any idea as to how I can save those geometry tensors to a file, so that I can set up a small code piece that loads this geometry and reproduces the TFG crash?

Btw given the bug I have with .numpy(), it seems to me there is a larger issue with tf.executing_eagerly()
tf.executing_eagerly() gives me a "True" but if it was really true I wouldn't have issues with .numpy() method

**Comment by julienvalentin** [comment]
Did you have a chance to try with TF1 if TF2 is facing problems at the moment?

**Comment by francoisruty** [comment]
my code is fully TF2 and I lack time to backport it to TF1, what I propose is that I'll try again once TF2 is officially released

**Comment by Johnny65456** [comment]
same problem

**Comment by julienvalentin** [comment]
Happy to take a look; can you generate a failing example on colab.research.google.com

**Comment by bq2139** [comment]
Same problem here with 2.0beta. `tf.executing_eagerly()` returns True but still 'Tensor' object has no attribute 'numpy'

**Comment by cem-keskin** [comment]
I've seen the same issue recently and then discovered that the .numpy() call was inside a function decorated with tf.function(). Once removed, it worked as expected.

**Comment by oracle3001** [comment]
I have a similar issue using TF 2.0 nightly

If I include the tfg.math.math_helpers.spherical_to_cartesian_coordinates operator in a keras model, it appears TF Graphics gets confused over whether things are operating eagerly or not.

I end up getting the following error,

  D:\Data\Documents\PyCharmProjects\learning_mesh_flows\joint_sample_optimization.py:53 calc_cart_coordinates  *
        return tfg.math.math_helpers.spherical_to_cartesian_coordinates(t_cv_sphere_spherical)
    C:\Users\Adam\Anaconda3\envs\tensorflow_nightly\lib\site-packages\tensorflow_graphics\math\math_helpers.py:135 spherical_to_cartesian_coordinates  *
        shape.check_static(
    C:\Users\Adam\Anaconda3\envs\tensorflow_nightly\lib\site-packages\tensorflow_graphics\util\shape.py:206 check_static  *
        if _get_dim(tensor, axis) != value:
    C:\Users\Adam\Anaconda3\envs\tensorflow_nightly\lib\site-packages\tensorflow_graphics\util\shape.py:135 _get_dim  *
        return tensor.shape[axis].value

    AttributeError: 'int' object has no attribute 'value'

and it all relates to the check for the dimensions, and it picks the wrong one part of the if / else. Getting rid of this static check and everything works fine.

**Comment by cem-keskin** [comment]
For the static shape check issue in _get_dim(), please check with the latest code from today to see if it is fixed.

For the more general issue about .numpy() not working in eager mode, check the following example:

import tensorflow as tf
tf.enable_eager_execution()
print(tf.executing_eagerly())  # prints True

@tf.function
def print_tensor(tensor):
  print(tf.executing_eagerly())  # prints False
  print(tensor.numpy())  # Fails with Attribute Error

a = tf.constant([1, 2, 3])
print_tensor(a)
>>>
True
False
AttributeError: 'Tensor' object has no attribute 'numpy'

Removing the tf.function decorator fixes this. Basically any call to numpy() should be outside the decorated function.

**Comment by julienvalentin** [comment]
I guess that this has been resolved thanks to Cem's help; closing this ticket. Feel free to re-open if needed.

**Comment by guanming001** [comment]
Hi I tried to run tensorflow-graphics with tensorflow 2.0.0-rc1
But I still encounter the error

~\Anaconda3\envs\dl2\lib\site-packages\tensorflow_graphics\util\shape.py in _get_dim(tensor, axis)
    133     return int(tf.shape(input=tensor).numpy()[axis])
    134   else:
--> 135     return tensor.shape[axis].value
    136 
    137 
AttributeError: 'int' object has no attribute 'value'

I have tried to replicate the error on colab by running the example ([6dof alignment.ipynb](https://colab.research.google.com/github/tensorflow/graphics/blob/master/tensorflow_graphics/notebooks/6dof_alignment.ipynb)) from tensorflow-graphics and added the below line to use tensorflow 2.0.0-rc1:
`
pip install tensorflow==2.0.0-rc1
`


And during the import step replace the line tf.enable_eager_execution() with:
`
tf.executing_eagerly() # For tf 2.0
`

**Comment by julienvalentin** [comment]
Could you create a toy example in Colab (https://colab.sandbox.google.com) which shows the issue and paste the link here?

thanks!

**Comment by guanming001** [comment]
@julienvalentin 
https://colab.research.google.com/drive/1tJsOGI2n8pOvjCjPLAgG2m5BkxulTn7i

**Comment by julienvalentin** [comment]
This is fixed in the github version, but not in the package until the next release.

This https://colab.sandbox.google.com/drive/1LE0I6qhPilwer5Zs-S7tjkwVxseUvtZK#scrollTo=u_W456-Xtewn to see how to manually apply that patch

**Comment by guanming001** [comment]
@julienvalentin  Thank you for your quick response!

**Comment by ehsuun** [comment]
Hi @julienvalentin could you please make the final link you posted public?
I have sort of the same issue. Using `vector.dot` in a loss function gives me the AttributeError: 'int' object has no attribute 'value' error in tf 2.0
https://colab.research.google.com/drive/1TTtNwEF4TjWQoXdvjpWky-dnXN1zFu13

**Comment by julienvalentin** [comment]
updated my message above to contain the fix

**Comment by peteflorence** [comment]
I ran into this issue on tensorflow 2.1.0, and tensorflow_graphics 1.0.0.
The fix by @julienvalentin worked for me. Since whitespace in Python matters, here it is copy-pastable:
```python
import sys

module = sys.modules['tensorflow_graphics.util.shape']
def _get_dim(tensor, axis):
    """Returns dimensionality of a tensor for a given axis."""
    return tf.compat.v1.dimension_value(tensor.shape[axis])

module._get_dim = _get_dim
sys.modules['tensorflow_graphics.util.shape'] = module
```
